# Generated by Django 2.2.5 on 2019-09-21 09:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'english'), ('ml', 'malayalam'), ('hi', 'hindi'), ('ta', 'tamil'), ('kn', 'kannada'), ('ur', 'urdu'), ('ma', 'marati')], default='', max_length=20),
        ),
    ]
