# Generated by Django 2.2.5 on 2019-09-21 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tito', '0002_translator_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='username',
        ),
        migrations.AddField(
            model_name='translator',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
