# Generated by Django 2.2.5 on 2019-09-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0003_auto_20190921_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='fullname',
        ),
    ]
