# Generated by Django 2.2.5 on 2019-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0007_auto_20190921_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='reputation',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
