# Generated by Django 2.2.5 on 2019-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0008_auto_20190921_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='reputation',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
