# Generated by Django 2.2.5 on 2019-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0009_auto_20190921_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='user',
        ),
        migrations.AddField(
            model_name='translator',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
