# Generated by Django 2.2.5 on 2019-09-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0010_auto_20190921_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranslationMessage',
            new_name='TranslationQuery',
        ),
        migrations.RenameField(
            model_name='translator',
            old_name='reputation',
            new_name='upvote',
        ),
    ]
