# Generated by Django 2.2.5 on 2019-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0011_auto_20190921_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationquery',
            name='message',
        ),
        migrations.AddField(
            model_name='translationquery',
            name='query',
            field=models.TextField(blank=True),
        ),
    ]
