# Generated by Django 2.2.5 on 2019-09-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0012_auto_20190921_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translator',
            old_name='message',
            new_name='response',
        ),
    ]
